# ========== DATABASE ==========
spring.datasource.url=jdbc:postgresql://localhost:5432/readify_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# ========== JPA / HIBERNATE ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ========== SERVER ==========
server.port=8080
